---
title: "Introduction to {tiotemp}"
author: "Mazama Science"
date: "September 25, 2020"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{tiotemp}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
  
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  fig.width = 7,
  fig.height = 7
)
```

The **tiotemp** R package is being developed by Mazama Science  to support the
presentation of environmental time series data with interactive visualization
components.

```{r}
library(tiotemp)
summary(example_airsensor_object)
```


```{r data}
data <- example_airsensor_object$data
meta <- example_airsensor_object$meta
```


Current components include:

## timeseriesMap

A Leaflet.js & D3.js based map.

```{r map}
timeseriesMap(data, meta)
```


## timeseriesBarChart

A Plotly.js based bar chart.

```{r barchart}
timeseriesBarChart(data, meta)
```

## timeseriesCalendar

A D3.js based calendar plot.

```{r calendar}
timeseriesCalendar(data, meta, full = FALSE)
```
