---
title: "examples_shiny"
author: "Mazama Science"
date: "7/29/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tiotemp)
library(AirSensor)
library(PWFSLSmoke)
library(shiny)
setArchiveBaseUrl("http://data.mazamascience.com/PurpleAir/v1") # SCAQMD sensors
sensors <- sensor_loadMonth(datestamp = 202003)
labels <- sensors$meta$label
monitors <- monitor_load(startdate = 20200101, enddate = 20200201)
breaks <- c(5, 10, 15, 20, 25, 30, 35, 40, 45, 50)
colors <- RColorBrewer::brewer.pal(10, "Spectral")
```


```{r interface, echo=FALSE}
inputPanel(
  selectInput("sensor", label = "Select Sensor",
              choices = labels)
  #dateRangeInput("dates", label = "Select Date Domain")
)
wellPanel(
  timeseriesMapOutput("map1")
)
wellPanel(
  timeseriesBarChartOutput("barchart1")
)
wellPanel(
  timeseriesCalendarOutput("calendar1")
)
wellPanel(
  timeseriesMapOutput("map2")
)
```

```{r map1, include=FALSE}
output$map1 <- renderTimeseriesMap({
  timeseriesMap(sensors$data, sensors$meta, inputId = "sensor", breaks = breaks, colors = colors, selected = 'SCAH_05')
})
```


```{r map2, include=FALSE}
output$map2 <- renderTimeseriesMap({
  timeseriesMap(monitors$data, monitors$meta, breaks = breaks, colors = colors)
})
# map2
```



```{r barchart, include=FALSE}
output$barchart1 <- renderTimeseriesBarChart({
  timeseriesBarChart(sensors$data, sensors$meta, inputId = 'sensor', colors = colors, breaks = breaks, ylab = "\u03bcg / m\u00b3")
})

```

```{r calendar, include=FALSE}
output$calendar1 <- renderTimeseriesCalendar({
  timeseriesCalendar(sensors$data, sensors$meta, inputId = 'sensor', colors = colors, breaks = breaks)
})
```

